In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

c = np.array([[1, 0, 2, 3], [4, 7, 6, 4], [5, 2, 1, 0]])

a.dot(c)

array([[24, 20, 17, 11],
       [54, 47, 44, 32]])

In [2]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[1, 2, 3], [4, 5, 6]])

a.dot(b)

array([[ 9, 12, 15],
       [24, 33, 42]])

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.T.dot(a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [6]:
c.T.dot(a.T)

array([[24, 54],
       [20, 47],
       [17, 44],
       [11, 32]])

In [8]:
x = np.array([[1, 2], [4, 5]])

(3* x).dot(x)

array([[27, 36],
       [72, 99]])